export const STATES = [
  'Andaman and Nicobar Islands',
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chandigarh',
  'Chhattisgarh',
  'Dadra and Nagar Haveli',
  'Daman and Diu',
  'Delhi',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jammu and Kashmir',
  'Jharkhand',
  'Kerala',
  'Karnataka',
  'Ladakh',
  'Lakshadweep',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Puducherry',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttarakhand',
  'Uttar Pradesh',
  'West Bengal',
];

export const STATE_CODE = [
  { state: 'Jammu and Kashmir', code: 1 },
  { state: 'Himachal Pradesh', code: 2 },
  { state: 'Punjab', code: 3 },
  { state: 'Chandigarh', code: 4 },
  { state: 'Uttarakhand', code: 5 },
  { state: 'Haryana', code: 6 },
  { state: 'Delhi', code: 7 },
  { state: 'Rajasthan', code: 8 },
  { state: 'Uttar Pradesh', code: 9 },
  { state: 'Bihar', code: 10 },
  { state: 'Sikkim', code: 11 },
  { state: 'Arunachal Pradesh', code: 12 },
  { state: 'Nagaland', code: 13 },
  { state: 'Manipur', code: 14 },
  { state: 'Mizoram', code: 15 },
  { state: 'Tripura', code: 16 },
  { state: 'Meghalaya', code: 17 },
  { state: 'Assam', code: 18 },
  { state: 'West Bengal', code: 19 },
  { state: 'Jharkhand', code: 20 },
  { state: 'Odisha', code: 21 },
  { state: 'Chhattisgarh', code: 22 },
  { state: 'Madhya Pradesh', code: 23 },
  { state: 'Gujarat', code: 24 },
  { state: 'Daman and Diu', code: 25 },
  { state: 'Dadra and Nagar Haveli', code: 26 },
  { state: 'Maharashtra', code: 27 },
  { state: 'Andhra Pradesh (Old)', code: 28 },
  { state: 'Karnataka', code: 29 },
  { state: 'Goa', code: 30 },
  { state: 'Lakshadweep', code: 31 },
  { state: 'Kerala', code: 32 },
  { state: 'Tamil Nadu', code: 33 },
  { state: 'Puducherry', code: 34 },
  { state: 'Andaman and Nicobar Islands', code: 35 },
  { state: 'Telangana', code: 36 },
  { state: 'Andhra Pradesh', code: 37 },
  { state: 'Ladakh', code: 38 },
];
